review
andreyshilov0/converter-currency pull request #1
Opened 2023-02-28 13:57 UTC by andreyshilov0

2023-02-28 19:26 UTC, Isidora25 requested changes
Замечание о названии ветки и сообщении коммита 
review - что-то слишком абстрактное и никак не отражает сути происходящего здесь 
как и сообщение первого коммита i 😄 
Для коммита с  исправлением замечаний исправь это, пожалуйста 
Сообщения для коммита пишутся  в повелительном наклонении

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +  const [toPrice, setToPrice] = useState(1);
1. Неизменяемые значения строк и чисел лучше выносить в переменные типа константа, которая именуется в UPPER_SNAKE_CASE
  например DEFAULT_FROM_CURRECNCY = "USD"
2.  имя стейта toPrice немного ставит в тупик, так как непонятно о какой цене речь. Имена переменных должны четко отображать ее назначение, так будет проще читать и понимать твой код другим разработчикам, а также самому будет проще вспомнить через какое-то время, что тут вообще происходит. Так как переменная предназначена для хранения  количества валюты, с которым мы собираемся работать, то предлагаю заменить слово price на amount

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +  };
отбивай, пожалуйста, смысловые блоки пробелами - так легче читается

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +    console.log(fromPrice);
все логи, комментарии и тому подобное стоит убирать перед отправкой на ревью

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +      <h1 className="App-header">Конвертер валют</h1>
имена класснеймов принято писать в kebab-case, то есть начинать со строчной буквы

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +        <div className="Symbol">=</div>
для текстового контента лучше использовать семантические теги, например p

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +        {" "}
не совсем понятно, зачем здесь дополнительная обертка с теми же классом Button?

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +        <u onClick={handleClick} className="Button">
Почему именно тэг u?) почему не b, не а?) 
Кажется, что это должно быть кнопкой.
Если элемент кликается и совешает какое-то действие без последующего редиректа - это кнопка
Если элемент кликается и редиректит юзера куда-то в другое место - это ссылка

то, как эти элементы выглядят в UI - абсолютно неважно, для этого у разработчика есть css

2023-02-28 19:26 UTC, Isidora25 commented on src/css/App.css
> +.App-header {
лучше отбивать каждый класс отступом, так проще читать

2023-02-28 19:26 UTC, Isidora25 commented on src/css/App.css
> +
лишний отступы наоборт - зло

2023-02-28 19:26 UTC, Isidora25 commented on src/css/App.css
> +}
а это прямо прямо любой элемент с этим классом принимает этот стиль?

2023-02-28 19:26 UTC, Isidora25 commented on src/css/App.css
> +  margin-bottom: 20px;
для правила margin есть сокращенная запись 

три строчки  
```
margin-left: 10px;
  margin-right: 10px;
  margin-bottom: 20px;
```

заменятся одной 
`
margin: 0 10px 20px;`

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +    fetch("https://www.cbr-xml-daily.ru/latest.js")
В тз речь шла вроде бы про другое API? 
я не вижу здесь использования ключа, а это нужно уметь правильно обрабатывать

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +      });
Все, что касается работы с api лучше выносить в отдельный файл

2023-02-28 19:26 UTC, Isidora25 commented on src/App.js
> +    console.log(fromPrice);
а для чего обновлять стейт количества валюты при изменении самой валюты?

2023-02-28 19:26 UTC, Isidora25 commented on src/Block.jsx
> +        ></input>
здесь можно обойтись без закрывающего тега, просто закрыв открывающий

2023-02-28 19:26 UTC, Isidora25 commented on src/css/index.css
> +}
Хм, не встретила ни одного тега code в данном ПРе
Не стоит хранить код, который не используется 
он раздувает бандл, а пользы не приносит
если он добавлен "на будущее", то очень часто это будущее не наступает и лучше делать все подобные изменения по факту использования

2023-03-01 11:57 UTC, Isidora25 requested changes
сообщение выглядит коммита уже лучше!  
Но правильно его писать в настоящем времени ;)

2023-03-01 11:57 UTC, Isidora25 commented on src/App.jsx
> +  const [DEFAULT_TO_CURRENCY, SET_DEFAULT_TO_CURRENCY] = useState("EUR");
кажется, ты меня неправильно понял, имена переменных состояний были в порядке. 
в константы нужно выносить дефолтовые значения  
SNAKE_UPPER_CASE используется только для неизменяемых значений
```
const DEFAULT_FROM_CURRENCY = "USD"
const [fromCurrancy, setFromCurrancy] = useState(DEFAULT_FROM_CURRENCY );
```

2023-03-01 11:57 UTC, Isidora25 commented on src/App.jsx
> +  const [DEFAULT_TO_CURRENCY, SET_DEFAULT_TO_CURRENCY] = useState("EUR");
Если по каким-то комментариям возникают вопросы, не стесняйся спрашивать, всегда готова дать пояснение

2023-03-01 11:57 UTC, Isidora25 commented on src/App.jsx
> +  const [toAmount, SetToAmount] = useState(1);
имена функций пишутся в camelCase `SetToAmount -> setToAmount`

2023-03-01 11:57 UTC, Isidora25 commented on src/App.jsx
> +  };
Лучше придерживаться одинакового подхода к написанию кода. Если ты аналогичную функцию для изменения валюты To кидаешь напрямую в проп, то и это логично кидать напрямую

2023-03-01 11:57 UTC, Isidora25 commented on src/Block.jsx
> +}) => {
Опять же, про единый стиль. Для компонента App ты используешь ключевое слово function, а здесь используешь стрелочную функцию. Давай выберем какой-то один подход, если иное не требуется условиями задачи

2023-03-01 11:57 UTC, Isidora25 commented on src/api/Apifixer.js
> +var myHeaders = new Headers();
не стоит использовать переменную var если ты пишешь новый проект и у тебя есть возможность использовать все возможности ES5-ES6

2023-03-01 11:57 UTC, Isidora25 commented on src/api/Apifixer.js
> +const apikey = process.env.REACT_APP_API_KEY;
для неизменяемых переменных используется UPPER_SNAKE_CASE

https://www.freecodecamp.org/news/when-to-capitalize-your-javascript-constants-4fabc0a4a4c4/

2023-03-01 11:57 UTC, Isidora25 commented on package.json
> +    "axios": "^1.3.4",
А для чего axios, если ты его не используешь совсем?
неиспользуемый код - это плохо, его не должно быть в проекте

2023-03-01 11:57 UTC, Isidora25 commented on src/api/Apifixer.js
> +var requestOptions = {
и это тоже не var, переменная не изменяется нигде

2023-03-01 11:57 UTC, Isidora25 commented on src/css/App.css
> +}
упс, тут что-то случилось с отступами

2023-03-01 11:57 UTC, Isidora25 commented on src/css/App.css
> +cursor: pointer;
кстати для тега button cursor: pointer; дефолтовое свойство

2023-03-01 12:59 UTC, Isidora25 requested changes
Вот теперь сообщение коммита норм) 
Было бы еще круче, если бы оно отражало суть твоих изменений

2023-03-01 12:59 UTC, Isidora25 commented on src/App.jsx
> +  const SET_DEFAULT_FROM_CURRENCY = "EUR";
Нет нужды создавать эти константы (как и любые константы) каждый раз при ререндере компонента App, пожалуйста, вынеси их из тела компонента как в компоненте Block

2023-03-01 13:04 UTC, reshetov requested changes

2023-03-01 13:04 UTC, reshetov commented on src/App.jsx
> +  const [toAmount, setToAmount] = useState(1);
А почему тут 1? У тебя 0 ед. FROM валюты превращается в 1 ед. TO валюты

2023-03-01 13:04 UTC, reshetov commented on src/App.jsx
> +  const [toCurrency, setToCurrency] = useState(SET_DEFAULT_FROM_CURRENCY);
1. Не используй (ну или постарайся) в констанстах SET/GET это префиксы который обозначают дейтсвия (сеттер и геттер), а у тебя просто хранится значение
2. Почему ты константу для поля TO назвал как FROM? не проще ли ее DEFAULT_TO_CURRENCY назвать?

2023-03-01 14:27 UTC, Isidora25 approved these changes

2023-03-02 09:23 UTC, merged